a=set(input("Enter the elements of the set 1: ").split())
b=set(input("Enter the elements of the set 2: ").split())
print("Set 1:",a)
print("Set 2:",b)
x=a.intersection(b)
print("Common elements that are present in both sets:",x)
y=a.union(b)
print("Unique elements in set 1:",a)
print("Unique elements in set 2:",b)
print("Union of two sets",a.union(b))
print("Subset of a set")